# trying a resnet18
# dataset params
data_dir: '/datadrive/bwfolder/data'
# data_dir: './data'
label_dir: '/datadrive/bwfolder/labels'
# label_dir: 'labels'
label_csv: {'train': 'Combined_All10k_Train.csv',
            'test': 'Combined_All10k_Test.csv',
            'val': 'Combined_All10k_Val.csv',
            'predict': 'Combined_BW10k_Train.csv'}
use_survey: ['pascal', 'cces']
sp_dict: {'ZC': 0,
          'BB': 1,
           'MS': 2,
           'BW43': 3,
           # 'BW37V': 4}
           'BW37V': 4,
           'BW': 5,
           'BW26-47': 6,
           'BW38': 7,
           'BWC': 8,
           'BWposs': 9,
           'BWunid': 10,
           'GG': 11,
           'GGposs': 12,
           'NBHF': 13,
           'OO': 14,
           'PM': 15,
           'SHIP': 16,
           'Ship': 17}
do_train: False
pred_test: True
model: 'r18'
check_na_col: ['wigMax', 'dBPP']
resume: True
extra_params: 0
# keeping num_classes as a separate arg in case we want to expand
# the sp_dict and only use a subset
num_classes: 5
model_save_dir: 'model_selnetv5clswtlam16.9'

# computer parameters
seed: 11211988
device: cuda
num_workers: 6

# training hyperparams
learning_rate: 0.005
weight_decay: 0.001
lr_step_count: 12
lr_step: .5
batch_size: 128
num_epochs: 50

# do pred with no plots only csv
simple_pred: True
# plot params
plot_top_n: 5
do_sal: False
pred_dir: 'pred_selnetv5clswtlam16.9'
do_dff: False
n_dff: 4
do_gradcam: False

# augmentation params
# set 0 to turn off
rndaff_transx: 0
rndaff_fill: 127
# set 1 to turn off 7 standard
gb_kernel: 1
gb_max: 2
weighted_sampler: False
weighted_loss: True
# 0, 1 for nothing
norm_mean: [.5, .5, .5]
norm_sd: [.046, .046, .046]
# min prob 1 to turn off
snr_scale_params: {'max_val': 30,
                   'min_prob': 1}
# set to like -10 to turn off
snr_filt_min: 5
# filter for high SNR vals
snr_trunc: 80
ici_max: 1
use_ici: True
ici_mult: 10
# selnet
do_selnet: True
sel_lambda: 16
sel_coverage: .9
sel_alpha: .5
