# trying a resnet18
# dataset params
# data_dir: '/datadrive/bwfolder/data'
data_dir: './data'
label_dir: '/datadrive/bwfolder/labels'
# label_dir: 'labels'
label_csv: {'train': 'PASCAL_BW_Train.csv',
            'test': 'PASCAL_BW_Test.csv',
            'val': 'PASCAL_BW_Val.csv',
            'predict': 'PASCAL_BW_Train.csv'}
sp_dict: {'ZC': 0,
          'BB': 1,
          'MS': 2,
          'BW43': 3,
          'BW37V': 4}
pred_test: False
check_na_col: ['wigMax', 'dBPP']
resume: True
extra_params: 1
# keeping num_classes as a separate arg in case we want to expand
# the sp_dict and only use a subset
num_classes: 5
model_save_dir: 'model_states_snr'

# computer parameters
seed: 11211988
device: cuda
num_workers: 4

# training hyperparams
learning_rate: 0.001
weight_decay: 0.001
lr_step_count: 8
lr_step: 1
batch_size: 128
num_epochs: 50

# plot params
plot_top_n: 5
pred_dir: 'export_preds_localtest'

# augmentation params
# set 0 to turn off
rndaff_transx: 0.0
rndaff_fill: 0
# set 1 to turn off
gb_kernel: 1
gb_max: 2
weighted_sampler: False
weighted_loss: True
# min prob 1 to turn off
snr_scale_params: {'max_val': 30,
                   'min_prob': .5}


