# trying a resnet18
# dataset params
data_dir: '/datadrive/bwfolder/data'
# data_dir: './data'
label_dir: '/datadrive/bwfolder/labels'
# label_dir: 'labels'
label_csv: {'train': 'Combined_BW10k_Train.csv',
            'test': 'Combined_BW10k_Test.csv',
            'val': 'Combined_BW10k_Val.csv',
            'predict': 'PASCAL_BW10k_Train.csv'}
use_survey: ['pascal', 'cces']
sp_dict: {'ZC': 0,
          'BB': 1,
           'MS': 2,
           'BW43': 3,
           'BW37V': 4}
pred_test: True
check_na_col: ['wigMax', 'dBPP']
resume: True
extra_params: 0
# keeping num_classes as a separate arg in case we want to expand
# the sp_dict and only use a subset
num_classes: 5
model_save_dir: 'model_comb10k_snr5normici10'

# computer parameters
seed: 11211988
device: cuda
num_workers: 6

# training hyperparams
learning_rate: 0.005
weight_decay: 0.001
lr_step_count: 20
lr_step: 1 
batch_size: 256
num_epochs: 90

# plot params
plot_top_n: 5
do_sal: False
pred_dir: 'pred_comb10k_snr5norm_ici10'
do_dff: True
n_dff: 4
do_gradcam: True

# augmentation params
# set 0 to turn off
rndaff_transx: 0
rndaff_fill: 127
# set 1 to turn off 7 standard
gb_kernel: 1
gb_max: 2
weighted_sampler: False
weighted_loss: True
# 0, 1 for nothing
norm_mean: [.5, .5, .5]
norm_sd: [.046, .046, .046]
# min prob 1 to turn off
snr_scale_params: {'max_val': 30,
                   'min_prob': 1}
# set to like -10 to turn off
snr_filt_min: 5
# filter for high SNR vals
snr_trunc: 80
ici_max: 1
use_ici: True
ici_mult: 10

