# dataset params
data_dir: './data'
label_dir: '.'
label_csv: {'train': 'PASCAL_BW_Train.csv',
            'test': 'PASCAL_BW_Test.csv',
            'val': 'PASCAL_BW_Val.csv'}
num_classes: 5

# computer parameters
device: cuda
num_workers: 4

# training hyperparams
learning_rate: 0.001
weight_decay: 0.001
batch_size: 128
num_epochs: 200